### ISSUE TITLE
migrate sonic 报错问题.

### ISSUE THREAD

**Issue by SilenceTiger** [gzydong/go-chat#14]
F:\code\IM\go-chat-master>go run ./cmd/lumenim migrate
# github.com/bytedance/sonic/internal/rt
C:\Users\Quarter\go\pkg\mod\github.com\bytedance\sonic@v1.10.2\internal\rt\gcwb.go:102:6: missing function body
C:\Users\Quarter\go\pkg\mod\github.com\bytedance\sonic@v1.10.2\internal\rt\gcwb.go:104:6: missing function body
C:\Users\Quarter\go\pkg\mod\github.com\bytedance\sonic@v1.10.2\internal\rt\gcwb.go:114:6: missing function body

**Comment by gzydong** [comment]
检测下你的本地环境版本，及安装的依赖

**Comment by SilenceTiger** [comment]
似乎sonic只支持 amd64  不支持 windows/386 ?
