### ISSUE TITLE
请教下，如何实现create_at和update_at时间的自动化处理的？

### ISSUE THREAD

**Issue by aohanhongzhi** [gzydong/go-chat#5]
![image](https://github.com/gzydong/go-chat/assets/37319319/3742100e-4f36-42e2-9eb2-a7ad7648dc21)

**Comment by gzydong** [comment]
这个是gorm 处理的自动填充

**Comment by aohanhongzhi** [comment]
我就是没有找到填充代码。很纳闷

**Comment by aohanhongzhi** [comment]
主要是插入数据库的时候，时区有点问题。因此想找到源码处，做调整。但是没有找到因此，只能全局设置东八区时间，

![image](https://github.com/gzydong/go-chat/assets/37319319/8033c143-28b8-47d2-a4f4-99d9c58760a1)


![image](https://github.com/gzydong/go-chat/assets/37319319/608da85e-33c1-44ac-8870-ffe5596d70b7)




调试源码都没有找到。
![image](https://github.com/gzydong/go-chat/assets/37319319/b7472edc-3260-4651-8682-ffe68e8c512b)

**Comment by aohanhongzhi** [comment]
人傻了，这个是GORM自己的默认实现，与本仓库代码无关。需要分析GORM里面源码。
